disallowed-methods = [
    { path = "axum::routing::get", reason = "x" },
    { path = "axum::routing::method_routing::get", reason = "x" },
    { path = "axum::routing::head", reason = "x" },
    { path = "axum::routing::method_routing::head", reason = "x" },
    { path = "axum::routing::post", reason = "x" },
    { path = "axum::routing::method_routing::post", reason = "x" },
    { path = "axum::routing::put", reason = "x" },
    { path = "axum::routing::method_routing::put", reason = "x" },
    { path = "axum::routing::delete", reason = "x" },
    { path = "axum::routing::method_routing::delete", reason = "x" },
    { path = "axum::routing::connect", reason = "x" },
    { path = "axum::routing::method_routing::connect", reason = "x" },
    { path = "axum::routing::options", reason = "x" },
    { path = "axum::routing::method_routing::options", reason = "x" },
    { path = "axum::routing::trace", reason = "x" },
    { path = "axum::routing::method_routing::trace", reason = "x" },
    { path = "axum::routing::patch", reason = "x" },
    { path = "axum::routing::method_routing::patch", reason = "x" },
]